version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: false
  file-lines:
    config:
      threshold: 300
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "client/semantic"
  - "api/data/mock-repository.js"
