FROM mhart/alpine-node:8.10.0

RUN apk update && apk add --no-cache bash python
RUN npm install -g pm2@latest
#ADD Entrypoint.sh /opt/
WORKDIR /opt/

EXPOSE 3000 3001 3002
ENTRYPOINT ["/bin/bash", "-ex", "/opt/efcsydney-roster/Entrypoint.sh", "dev"]
