FROM mhart/alpine-node:8.10.0
RUN apk update && apk add --no-cache bash py-pip
RUN npm install -g pm2@latest

ADD ./efcsydney-roster.tar.gz /opt/
WORKDIR /opt/efcsydney-roster

RUN pip install awscli --upgrade --user && \
    echo "export PATH=$PATH:~/.local/bin/" >> ~/.bashrc

EXPOSE 3000 3001 3002
ENTRYPOINT ["/bin/bash", "-ex", "/opt/efcsydney-roster/Entrypoint.sh"]
