version: "3"
services:
  db:
    image: mysql:5.7.21
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "password"
        MYSQL_DATABASE: "efcRoster"

  efc-dev:
    image: efc-roster:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
    links:
        - db:db
    environment:
        - NODE_ENV=docker
    ports:
      - "80:80"
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - $PWD:/opt/efcsydney-roster/

  efc-prod:
    image: efc-roster:latest
    build:
      context: .
      dockerfile: Dockerfile-prod
    links:
        - db:db
    environment:
        - NODE_ENV=qa
    ports:
      - "80:80"
      - "3001:3001"
      - "3002:3002"
    entrypoint:
      - /bin/bash
      - -x
      - /opt/efcsydney-roster/Entrypoint.sh
      - prod-local
