FROM mhart/alpine-node:8.12.0


ARG REACT_APP_ENV=qa
ENV REACT_APP_ENV=${REACT_APP_ENV}

RUN apk update && apk add --no-cache bash py-pip jq
RUN npm install -g npm@5.6.0 && npm install -g pm2@latest
RUN apk add mysql-client


RUN pip install awscli --upgrade --user && \
    echo "export PATH=$PATH:~/.local/bin/" >> ~/.bashrc


COPY ./ /opt/efcsydney-roster/
RUN ls /opt/efcsydney-roster/
WORKDIR /opt/efcsydney-roster
RUN yarn

WORKDIR /opt/efcsydney-roster/client
RUN yarn ; yarn build ; rm -rf ./node_modules

WORKDIR /opt/efcsydney-roster

EXPOSE 3000 3001 3002
ENTRYPOINT ["/bin/bash", "-ex", "/opt/efcsydney-roster/docker/Entrypoint.sh", "prod"]
